name: project-app-team-repo

services:
  app:
    build: ./app
    container_name: web-app
    hostname: web-app
    volumes: ["./app/src:/appcode"]
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 8501:8501

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    env_file:
      - ./api/.env
    # volumes: ["./api:/apicode"]
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 4000:4000

  db:
    env_file:
      - ./api/.env
    build: ./mysql-init
    container_name: mysql_db
    hostname: db
    volumes:
      - "mysql_data:/var/lib/mysql"
    ports:
      - "3200:3306"

volumes:
  mysql_data:
